version: "1"
migration:
  dryRun: false
  concurrency: 5
  failureMode: "continue"
source:
  type: "JFROG"
  endpoint: "https://org.jfrog.io/artifactory"
  credentials:
    username: "${JFROG_USERNAME}"
    password: "${JFROG_PASSWORD}"
  filters:
    registries:
      - "my-python-reg"
      - "my-maven-reg"
    artifactNamePatterns:
      include:
        - ".*:stable"
      exclude:
        - ".*:experimental"
    artifactTypes:
      - "maven"
      - "python"
destination:
  type: "HAR"
  accountIdentifier: "myaccount"
  registryEndpoint: "pkg.harness.io"
  credentials:
    username: "${DESTINATION_USERNAME}"
    token: "${DESTINATION_TOKEN}"
  mappings:
    - sourceRegistry: "my-python-reg"
      destinationRegistry: "myorg/my-python-prod"
    - sourceRegistry: "my-maven-reg"
      destinationRegistry: "myorg/my-maven"
