version: 1.0.0
dryRun: false
concurrency: 1
failureMode: continue
source:
  endpoint: ${SRC_ENDPOINT}
  type: JFROG
  credentials:
    username: ${SRC_USER}
    password: ${SRC_PASS}
    token: ${SRC_TOKEN}
destination:
  endpoint: ${DST_ENDPOINT}
  type: HAR
  credentials:
    username: ${DST_USER}
    password: ${DST_PASS}
    token: ${DST_TOKEN}
mappings:
  - artifactType: ${ARTIFACT_TYPE}
    sourceRegistry: ${SRC_REG}
    destinationRegistry: ${DST_REG}
    includePatterns:
      - '*'
    excludePatterns:
      - abc
      - def