version: 1.0.0
dryRun: false
concurrency: 5
failureMode: continue
source:
  endpoint: ${SRC_ENDPOINT}
  type: JFROG
  credentials:
    username: ${SRC_USER}
    password: ${SRC_PASS}
destination:
  endpoint: ${DST_ENDPOINT}
  type: HAR
  credentials:
    username: ${DST_USER}
    password: ${DST_PASS}
mappings:
  - artifactType: HELM_LEGACY
    sourceRegistry: src
    destinationRegistry: dst
  - artifactType: DOCKER
    sourceRegistry: src
    destinationRegistry: dst
  - artifactType: PYTHON
    sourceRegistry: src
    destinationRegistry: dst
  - artifactType: HELM
    sourceRegistry: src
    destinationRegistry: dst
  - artifactType: MAVEN
    sourceRegistry: src
    destinationRegistry: dst
  - artifactType: GENERIC
    sourceRegistry: src
    destinationRegistry: dst