version: 1.0.0
dryRun: false
concurrency: 5
failureMode: continue
source:
  endpoint: ${SRC_ENDPOINT}
  type: NEXUS
  credentials:
    username: ${SRC_USER}
    password: ${SRC_PASS}
  insecure: true
destination:
  endpoint: ${DST_ENDPOINT}
  type: HAR
  credentials:
    username: ${DST_USER}
    password: ${DST_PASS}
mappings:
#  - artifactType: HELM_LEGACY
#    sourceRegistry: src
#    destinationRegistry: dst
#    ref: /
  - artifactType: HELM_LEGACY
    sourceRegistry: tathagat-test
    destinationRegistry: helm-nexus
#  - artifactType: MAVEN
#    sourceRegistry: maven-internal-prod
#    destinationRegistry: maven-nexus

#    ref: /org
#  - artifactType: PYTHON
#    sourceRegistry: test_python
#    destinationRegistry: mypythonnexus
#    ref: /org/project
#  - artifactType: HELM
#    sourceRegistry: src
#    destinationRegistry: dst
#    ref: /org/project
#  - artifactType: MAVEN
#    sourceRegistry: src
#    destinationRegistry: dst
#    ref: /org/project
#  - artifactType: GENERIC
#    sourceRegistry: src
#    destinationRegistry: dst
#    ref: /org/project
#  - artifactType: NUGET
#    sourceRegistry: src
#    destinationRegistry: dst
#    ref: /org/project
#  - artifactType: NPM
#    sourceRegistry: src
#    destinationRegistry: npm
#    ref: /org/project